config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # We define themes where users choose 5 themes and confirm with a button
  resources :themes, only: [:index] do
    resources :topics, only: [:index]
  end
  get :chatrooms, to: "topics#chatrooms"
  resources :topics, only: [:index,:show, :new, :create] do
    member do
      post :send_ia_generated_message
    end
    resources :messages, only: [:create]
    resources :user_topics, only: [:create]
  end
  # resources :reviews, only: [:new, :create]
  resources :user_topics, only: [:update] do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:update, :show]
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :theme
  has_many :user_topics, dependent: :destroy
  # has_many :reviews, though: :user_topics
  has_many :messages, dependent: :destroy
  has_many :users, through: :user_topics

  after_create :create_user_topic_for_owner

  def reviews
    Review.where(reviewee_id: self.user_topics.pluck(:id)).or(Review.where(reviewer_id: self.user_topics.pluck(:id))).distinct
  end

  include PgSearch::Model
  pg_search_scope :search,
    against: [ :name, :description],
    associated_against: {
      theme: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  private

  def create_user_topic_for_owner
    UserTopic.create(user: self.user, topic: self, status: true)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topic = Topic.where.not(user: current_user)
    @topics = if params[:query].present?
                @topic.search(params[:query])
              else
                @topic.all
              end
    @topics = @topics.select { |topic| topic.user_topics.count == 1 }
    @topics = Topic.where(id: @topics.map(&:id)).order(created_at: :desc)

    @user_themes_topics = @topics.joins(:theme).where(themes: { id: current_user.themes.pluck(:id) })
    @other_themes_topics = @topics.where.not(id: @user_themes_topics.pluck(:id))
    @available_topics = @user_themes_topics + @other_themes_topics
  end

  def chatrooms
    @topics = current_user.joined_topics
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.build(topic_params)
    @topic.user = current_user

    if @topic.save
      redirect_to topics_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @topic = Topic.find(params[:id])
    @current_user_topic = @topic.user_topics.where(user_id: current_user.id).first
    @reviewee_user_topic = @topic.user_topics.where.not(user_id: current_user.id).first
    @message = Message.new
  end

  def send_ia_generated_message
    @topic = Topic.find(params[:id])
    message_content = AskIaForAnswer.new(@topic).call
    @message = Message.new(content: message_content)
    @user_topic = @topic.user_topics.find_by(user: current_user)
    @message.user_topic = @user_topic
    @message.topic = @topic

    if @message.save
      TopicChatroomChannel.broadcast_to(
        @topic,
        message: render_to_string(partial: "messages/message", locals: { message: @message }),
        sender_id: @message.user.id
      )
    end
    head :ok
  end

  def destroy

  end

  private

  def topic_params
    params.require(:topic).permit(:name, :description, :theme_id, :user_id)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/views/topics/_card.html.erb
<div class="card-topic">
  <div class="card-topic-info">
    <div class="card-topic-info-name">
      <div class="title d-inline-block mb-3"><%= topic.theme.name %></div>
      <p><strong><%= topic.name %></strong>
        <% if current_page?(action: "chatrooms") %>
          <i class="ms-2 fa-solid fa-circle-info d-none" data-bs-toggle="modal" data-bs-target="#modal<%= topic.id %>"></i>
        <% else %>
          <i class="ms-2 fa-solid fa-circle-info" data-bs-toggle="modal" data-bs-target="#modal<%= topic.id %>"></i>
        <% end %>
      </p>
    </div>
  </div>
  <div class="card-topic-user">
    <%= render "shared/avatar_with_badge", user: topic.user, size: :small %>
    <p class="mt-2 mb-0"><%= topic.user.username.capitalize %></p>
  </div>
</div>

app/views/topics/_chatroom.html.erb
<div class="chat-container">

  <div class="chat-messages" data-topic-subscription-target="messages">
    <% @topic.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
        <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>
  <div>
  <% if @current_user_topic.status == true %>
    <%= simple_form_for [@topic, @message],
      html: { data: { action: "turbo:submit-end->topic-subscription#resetForm" }, class: "d-flex gap-1 mb-2" } do |f|
    %>
      <%= f.input :content,
        label: false,
        placeholder: "Type your message here",
        wrapper_html: {class: "flex-grow-1 mb-0"},
        input_html: {class: "input-send", autocomplete: "off"} %>
      <%= button_tag class: 'button-send' do %>
        <i class="fa-regular fa-paper-plane fa-2xl"></i>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/topics/_modal.html.erb
<!-- Scrollable modal -->
<div class="modal fade " id="modal<%= topic.id %>" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content modal-style">
      <div class="modal-header">
        <h5 class="modal-title"><%= topic.name %></h5>
      </div>
      <div class="modal-body">
        <p><%= topic.description %></p>
      </div>
      <div class="modal-footer">
        <%= link_to  "Back", topics_path, class: "btn btn-outline-light rounded-5" %>
        
        <% unless current_user.in?(topic.users) %>
          <%= link_to topic_user_topics_path(topic), data: { turbo_method: :post }, class: "btn styled-button" do %>
            <i class="fa-regular fa-comments">  JOIN</i>
          <% end %>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/topics/chatrooms.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="mt-3 mb-2">Your current chatrooms</h1>
    <div class="mb-5">
      <%= simple_form_for :truc, url: chatrooms_path, method: :get, html: { class: "chatrooms-filter" } do |f| %>
        <%= f.input :topic_type,
          label: false,
          collection: ['Active', 'Old'],
          selected: 'Active',
          include_hidden: false,
          include_blank: false,
          input_html: {
            class: "rounded-pill text-white"
          } %>
      <% end %>
    </div>
    <% if @topics.present? %>
      <% @topics.each do |topic| %>
        <div class="mb-3 chatroom-topic-container">
          <%= link_to "", topic_path(topic) if topic.users.count > 1 %>
          <div class="head-card">
            <small><em class="text-muted"><%= distance_of_time_in_words_to_now(topic.created_at) %> ago</em></small>
            <small><em class="text-muted"><%= topic.messages.count %> messages</em></small>
          </div>
          <%= render "topics/card", topic: topic %>
        </div>
      <% end %>
    <% else %>
      <p>You haven't any active topic right now.</p>
    <% end %>
    </div>
  </div>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="text-center">
    <h1 class="mt-3 mb-2">Browse current topics</h1>
    <div class="mb-5">
      <%= form_with url: topics_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control rounded-4",
          placeholder: "Start Your Search" %>
        <div>
          <%= button_tag class: "btn btn-search border border-light rounded-4" do %>
              <i class="fa-solid fa-eye"></i>
          <% end %>
          <%#= submit_tag "Search", name: "", class: "btn btn-search border border-light rounded-4"%>
        </div>
      <% end %>
    </div>
    <% if @available_topics.present? %>
      <% @available_topics.each do |topic| %>
        <%= render "topics/card", topic: topic %>
        <%= link_to topic_user_topics_path(topic), data: { turbo_method: :post }, class: "styled-button" do %>
          <i class="fa-regular fa-comments">  JOIN</i>
        <% end %>
        <%= render partial: 'topics/modal', locals: { topic: topic } %>
      <% end %>
    <% else %>
      <p>There are no topic matching your favorite themes for the moment.</p>
    <% end %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container text-white">
  <div class="row d-flex justify-content-center text-center">
    <div class="col-10">
      <h4 class="mb-4 mt-4">
        Create a new topic <%#= @current_user.topics %>
      </h4>
      <%= simple_form_for [@current_user, @topic] do |f| %>
        <%= f.input :theme_id, collection: Theme.all, label: false, prompt: "Select a theme", input_html: { data: { controller: "select2" } } %>
        <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :name, label: false, placeholder: "What is the name of your topic?"%>
        <%= f.input :description, label: false, placeholder: "Give a description of your topic", input_html: { rows: 4 } %>
        <%= f.button :submit, "Create Topic", class: "btn btn-secondary rounded-2" %>
      <% end %>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container" 
  id="topics-show"
  data-controller="topic-subscription"
  data-topic-subscription-topic-id-value="<%= @topic.id %>"
  data-topic-subscription-pamm-value="<%= false %>"
  data-topic-subscription-send-pamm-message-path-value="<%= send_ia_generated_message_topic_path(@topic) %>"
  data-topic-subscription-current-user-id-value="<%= current_user.id %>">
  <div class="mt-3">
    <%= render "topics/card", topic: @topic %>
  </div>
  <%= render "topics/chatroom" %>
  <%= render partial: 'topics/modal', locals: { topic: @topic } %>
  <div class="d-flex px-2 gap-2">
    <%= link_to "✋", '#', 
      class: "flex-grow-0 btn btn-outline-light rounded-4",
      data: { action: "click->topic-subscription#togglePamm"} %>
    <%= link_to "Review", new_user_topic_review_path(@reviewee_user_topic), class: "flex-grow-1 btn btn-outline-light rounded-4" %>
    <% if @current_user_topic.status == true %>
      <%= link_to "Leave", user_topic_path(@current_user_topic), data: { turbo_method: :patch }, class: "flex-grow-1 btn btn-light rounded-4" %>
    <% end %>
  </div>
</div>

app/views/topics/topics.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container profile-page">
    <div class="row">
        <div class="col-xl-6 col-lg-7 col-md-12">
            <div class="card profile-header">
                <div class="body">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-12">
                            <div class="profile-image float-md-right"> <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt=""> </div>
                        </div>
                        <div class="col-lg-8 col-md-8 col-12">
                            <h4 class="m-t-0 m-b-0"><strong>Michael</strong> Deo</h4>
                            <span class="job_post">Ui UX Designer</span>
                            <p>795 Folsom Ave, Suite 600 San Francisco, CADGE 94107</p>
                            <div>
                                <button class="btn btn-primary btn-round">Follow</button>
                                <button class="btn btn-primary btn-round btn-simple">Message</button>
                            </div>
                            <p class="social-icon m-t-5 m-b-0">
                                <a title="Twitter" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                                <a title="Facebook" href="javascript:void(0);"><i class="fa fa-facebook"></i></a>
                                <a title="Google-plus" href="javascript:void(0);"><i class="fa fa-twitter"></i></a>
                                <a title="Behance" href="javascript:void(0);"><i class="fa fa-behance"></i></a>
                                <a title="Instagram" href="javascript:void(0);"><i class="fa fa-instagram "></i></a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>