config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # We define themes where users choose 5 themes and confirm with a button
  resources :themes, only: [:index] do
    resources :topics, only: [:index]
  end
  get :chatrooms, to: "topics#chatrooms"
  resources :topics, only: [:index,:show, :new, :create] do
    member do
      post :send_ia_generated_message
    end
    resources :messages, only: [:create]
    resources :user_topics, only: [:create]
  end
  # resources :reviews, only: [:new, :create]
  resources :user_topics, only: [:update] do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:update, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one_attached :avatar
  has_many :topics, dependent: :destroy

  has_many :user_topics, dependent: :destroy
  has_many :joined_topics, through: :user_topics, source: :topic
  has_many :reviews_as_reviewee, through: :user_topics

  has_many :user_themes, dependent: :destroy
  has_many :themes, through: :user_themes

  has_one :user_grade, dependent: :destroy

  validates :username, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    current_user.update(user_params)
    redirect_to topics_path
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json {
        render json: { html: render_to_string(partial: "users/show", locals: { user: @user }, formats: :html) }.to_json
      }
    end
  end

  def update_avatar
    @user = current_user
    @user.avatar.attach(params[:avatar])
    redirect_to @user, notice: 'Avatar updated succesfully.'
  end

  private

  def user_params
    params.require(:user).permit(theme_ids: [])
  end
end

app/views/users/_show.html.erb
<%
  average_interesting_note = user.reviews_as_reviewee.average(:interesting).to_i
  average_fun_note = user.reviews_as_reviewee.average(:fun).to_i
  average_nice_note = user.reviews_as_reviewee.average(:nice).to_i
%>

<div class="container">
  <div class="d-flex gap-2 mt-3 mb-5 ">
  <div class="me-4 align-items-center d-flex">
    <%= render 'shared/avatar_with_badge', user: user %>
  </div>
  <div class="username-description">
    <div class="d-flex">
      <h1><%= user.username.capitalize %></h1>
    </div>
    <p><%= user.description || 'Here for both laughs and deep discussions. Let\'s chat about life\'s absurdities and its profound mysteries. 🤪🤔' %></p>
    <% if user == current_user %>
      <%= link_to 'Sign out', destroy_user_session_path, class: 'styled-button mt-3 d-inline-block fw-bold', data: {turbo_method: :delete} %>
    <% end %>
  </div>
  </div>

  <div class="d-flex align-items-baseline pt-4"><h2 style="margin-right: 20px">Favorite themes</h2>
    <% if user == current_user %>
      <%= link_to themes_path do%>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
    <% end %>
   </div>
  <div class="mb-5 mt-4">
    <% user.themes.each do |theme| %>
      <div class="badge rounded-pill styled-button gradient gap-4 mb-1">
        <div class="theme">
          <%= theme.name %>
        </div>
      </div>
    <% end %>
  </div>



  <h2 class="mt-3">Reviews</h2>
    <div class="mt-3">
      <div class="col-12 d-flex justify-content-center gap-1">
        <div class="text-align-center">
        <div class="emoji">
          🤔
        </div>
          <p class="emoji-text">Interet</p>
          <p class="rating"><%= average_interesting_note %>/5</p>
        </div>
        <div class="text-align-center">
          <div class="emoji">
            😂
          </div>
          <p class="emoji-text">Fun</p>
          <p class="rating"><%= average_fun_note %>/5</p>
        </div>
        <div class="text-align-center">
          <div class="emoji">
            😇
          </div>
          <p class="emoji-text">Nice</p>
          <p class="rating"><%= average_nice_note %>/5</p>
        </div>
    </div>
  </div>
  <% if user.reviews_as_reviewee.empty? %>
    No reviews yet...
  <% else %>
    <% user.reviews_as_reviewee.last(5).each do |review| %>
      <div class="profile-review-card mb-2">
        <div class="profile-review-card__author">
          <%= render "shared/avatar_with_badge", user: review.reviewer, size: :small %>
          <div class="profile-review-card__author__username"><%= review.reviewer.username.capitalize %></div>

        </div>
        <div class="profile-review-card__content">
          <p><%= review.topic.name %></p>
          <p><%= review.content %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "users/show", user: @user %>