config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # We define themes where users choose 5 themes and confirm with a button
  resources :themes, only: [:index] do
    resources :topics, only: [:index]
  end
  get :chatrooms, to: "topics#chatrooms"
  resources :topics, only: [:index,:show, :new, :create] do
    member do
      post :send_ia_generated_message
    end
    resources :messages, only: [:create]
    resources :user_topics, only: [:create]
  end
  # resources :reviews, only: [:new, :create]
  resources :user_topics, only: [:update] do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:update, :show]
end

app/views/shared/_avatar_with_badge.html.erb
<div data-controller="user-show-modal" data-user-show-modal-path-value="<%= user_path(user) %>">
  <div class="avatar-with-badge <%= "small" if local_assigns[:size] %>" data-action="click->user-show-modal#show">
    <% avatar = ["avatar-1.png", "avatar-2.png","avatar-3.png","avatar-4.png",
    "avatar-5.png","avatar-6.png","avatar-7.png","avatar-8.png", "avatar-9.png","avatar-10.png"] %>
    <%#= image_tag("avatars/#{avatar.sample}", class: 'avatar-large', alt: 'avatar') %>
    <%= image_tag("https://api.multiavatar.com/#{user.username}.png?apikey=#{ENV["AVATAR_API_KEY"]}", class: 'avatar-large', alt: 'avatar') %>
    <% if user.user_grade.present? %>
      <i class="<%= UserGrade::GRADES[user.user_grade.name] %>"></i>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <% if user_signed_in? %>
    <ul>
      <li>
        <%= link_to user_path(current_user), class: "navbar-brand" do %>
          <i class="fa-regular fa-user"></i>
        <% end %>
      </li>

      <li>
        <%= link_to new_topic_path, class: "navbar-brand" do %>
          <i class="fa-solid fa-plus"></i>
        <% end %>
      </li>
      <li>
        <%= link_to topics_path, class: "navbar-brand" do %>
         <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </li>
       <li>
        <%= link_to chatrooms_path, class: "navbar-brand" do %>
          <i class="fa-regular fa-comments"></i>
        <% end %>
      </li>
    </ul>
  <% end %>
</div>


<!-- Scrollable modal -->
<div class="modal fade" id="user-modal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content modal-style">
      <!-- Bouton de fermeture (close button) -->
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer">
        <i class="fa-solid fa-xmark fa-2xl" style="color: #ffffff;"></i>
      </button>
      <div class="modal-body" id="user-modal-body">
        <!-- Contenu de votre modal -->
      </div>
    </div>
  </div>
</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
  <div>
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag("Logo/Logo-PAMM.png")%>
    <% end %>
  </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div>
            <%#= link_to "#", class: "navbar-brand" do %>
              <%= form_with url: topics_path, method: :get, class: "d-flex" do %>
                <%= text_field_tag :query,
                  params[:query],
                  class: "form-control",
                  placeholder: "Start Your Search 🔍" %>
                <%= button_tag , class: "btn btn-primary" do %>
                   <i class="fa-solid fa-eye"></i>
                <% end %>
              <% end %>
            <%# end %>
          </div>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", "#", class: "dropdown-item" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>